# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BreadBasket_DMS.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BreadBasket_DMS.proto',
  package='BreadBasket',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x42readBasket_DMS.proto\x12\x0b\x42readBasket\"L\n\x0bTransaction\x12\x0c\n\x04\x44\x61te\x18\x01 \x02(\t\x12\x0c\n\x04Time\x18\x02 \x02(\t\x12\x13\n\x0bTransaction\x18\x03 \x02(\x05\x12\x0c\n\x04Item\x18\x04 \x02(\t')
)




_TRANSACTION = _descriptor.Descriptor(
  name='Transaction',
  full_name='BreadBasket.Transaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Date', full_name='BreadBasket.Transaction.Date', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Time', full_name='BreadBasket.Transaction.Time', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Transaction', full_name='BreadBasket.Transaction.Transaction', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Item', full_name='BreadBasket.Transaction.Item', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['Transaction'] = _TRANSACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), dict(
  DESCRIPTOR = _TRANSACTION,
  __module__ = 'BreadBasket_DMS_pb2'
  # @@protoc_insertion_point(class_scope:BreadBasket.Transaction)
  ))
_sym_db.RegisterMessage(Transaction)


# @@protoc_insertion_point(module_scope)
